### ISSUE TITLE
Register Constraints Need to be Added

### ISSUE THREAD

**Issue by marchsabino** [marchsabino/mwd-final#84]
### `User#register()`: 

Although MySQL will reject invalid constraints defined in the table's schema, we never actually tell the user what the constraints are.  Since we already handle this error, the backend (i.e. `User#register()`) will **not** have to be changed.  

**However**

`signup.pug` __will__ need to enforce the following constraints:

- [x] `username` 12 characters max

- [x] `email` 60 characters max

- [x] `fname` 15 characters max

- [x] `lname` 15 characters max

**Comment by eSeyana** [comment]
Completed and working.
